import os
def w(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content.strip() + '\n')
tm = 'C:/Users/Asus/OneDrive/Desktop/khatta/garg-store/src/main/resources/templates/'

w(tm+'suppliers/list.html', '''<!DOCTYPE html><html xmlns:th="http://www.thymeleaf.org"><head th:replace="~{layout :: head('Suppliers')}"></head><body><div th:replace="~{layout :: sidebar}"></div><div class="content"><h1>Suppliers <a href="/suppliers/new" class="btn">+ Add</a></h1><table><tr><th>Code</th><th>Name</th><th>Phone</th></tr><tr th:each="s : "><td th:text=""></td><td th:text=""></td><td th:text=""></td></tr></table></div></body></html>''')

w(tm+'suppliers/form.html', '''<!DOCTYPE html><html xmlns:th="http://www.thymeleaf.org"><head th:replace="~{layout :: head('Supplier Form')}"></head><body><div th:replace="~{layout :: sidebar}"></div><div class="content"><h1>Supplier Form</h1><form th:action="" method="post"><div th:if="">Code: <input type="text" name="supplierCode" required/></div><div>Name: <input type="text" name="name" th:value="" required/></div><div>Phone: <input type="text" name="phoneNo" th:value=""/></div><button type="submit" class="btn">Save</button></form></div></body></html>''')

w(tm+'sales/list.html', '''<!DOCTYPE html><html xmlns:th="http://www.thymeleaf.org"><head th:replace="~{layout :: head('Sales')}"></head><body><div th:replace="~{layout :: sidebar}"></div><div class="content"><h1>Sales <a href="/sales/new" class="btn">+ New Sale</a></h1><table><tr><th>Bill No</th><th>Date</th><th>Client</th><th>Total</th><th>Due</th></tr><tr th:each="s : "><td th:text=""></td><td th:text=""></td><td th:text=""></td><td th:text=""></td><td th:text=""></td></tr></table></div></body></html>''')

w(tm+'sales/form.html', '''<!DOCTYPE html><html xmlns:th="http://www.thymeleaf.org"><head th:replace="~{layout :: head('New Sale')}"></head><body><div th:replace="~{layout :: sidebar}"></div><div class="content"><h1>New Sale</h1><form action="/sales" method="post"><div>Bill No: <input type="text" name="billNo" required/> Date: <input type="date" name="billDate" required/> Client: <select name="clientCode"><option th:each="c : " th:value="" th:text=""></option></select> Payment Mode: <select name="paymentMode"><option>Cash</option><option>Credit</option></select></div><hr/><h3>Items</h3><div id="items"><div>Item: <select name="itemCode"><option value="">--</option><option th:each="i : " th:value="" th:text=""></option></select> Qty: <input type="number" name="quantitySold" value="1"/> Rate: <input type="number" step="0.01" name="rateApplied"/></div></div><button type="submit" class="btn">Submit Sale</button></form></div></body></html>''')

w(tm+'purchases/list.html', '''<!DOCTYPE html><html xmlns:th="http://www.thymeleaf.org"><head th:replace="~{layout :: head('Purchases')}"></head><body><div th:replace="~{layout :: sidebar}"></div><div class="content"><h1>Purchases <a href="/purchases/new" class="btn">+ New Purchase</a></h1><table><tr><th>Bill No</th><th>Date</th><th>Total</th></tr><tr th:each="p : "><td th:text=""></td><td th:text=""></td><td th:text=""></td></tr></table></div></body></html>''')

w(tm+'purchases/form.html', '''<!DOCTYPE html><html xmlns:th="http://www.thymeleaf.org"><head th:replace="~{layout :: head('New Purchase')}"></head><body><div th:replace="~{layout :: sidebar}"></div><div class="content"><h1>New Purchase</h1><form action="/purchases" method="post"><div>Bill No: <input type="text" name="purchaseBillNo" required/> Date: <input type="date" name="billDate" required/> Supplier: <select name="supplierCode"><option th:each="s : " th:value="" th:text=""></option></select> Paid: <input type="number" name="amountPaid" value="0"/></div><hr/><h3>Items</h3><div id="items"><div>Item: <select name="itemCode"><option value="">--</option><option th:each="i : " th:value="" th:text=""></option></select> Qty: <input type="number" name="quantity" value="1"/> Rate: <input type="number" step="0.01" name="rate"/></div></div><button type="submit" class="btn">Submit Purchase</button></form></div></body></html>''')

w(tm+'payments/list.html', '''<!DOCTYPE html><html xmlns:th="http://www.thymeleaf.org"><head th:replace="~{layout :: head('Payments')}"></head><body><div th:replace="~{layout :: sidebar}"></div><div class="content"><h1>Payments <a href="/payments/new" class="btn">+ Receive</a></h1><table><tr><th>Receipt</th><th>Date</th><th>Client</th><th>Amount</th></tr><tr th:each="p : "><td th:text=""></td><td th:text=""></td><td th:text=""></td><td th:text=""></td></tr></table></div></body></html>''')

w(tm+'payments/form.html', '''<!DOCTYPE html><html xmlns:th="http://www.thymeleaf.org"><head th:replace="~{layout :: head('Receive Payment')}"></head><body><div th:replace="~{layout :: sidebar}"></div><div class="content"><h1>Receive Payment</h1><form action="/payments" method="post">Receipt No: <input type="text" name="receiptNo" required/> Date: <input type="date" name="dateReceived" required/> Client: <select name="clientCode"><option th:each="c : " th:value="" th:text=""></option></select> Amount: <input type="number" step="0.01" name="amountReceived" required/> Mode: <select name="paymentMode"><option>Cash</option><option>Cheque</option><option>Online Transfer</option></select><button type="submit" class="btn">Save</button></form></div></body></html>''')

w(tm+'reports/index.html', '''<!DOCTYPE html><html xmlns:th="http://www.thymeleaf.org"><head th:replace="~{layout :: head('Reports')}"></head><body><div th:replace="~{layout :: sidebar}"></div><div class="content"><h1>Reports</h1><p>Module implementation as requested.</p></div></body></html>''')
w(tm+'employees/list.html', '''<!DOCTYPE html><html xmlns:th="http://www.thymeleaf.org"><head th:replace="~{layout :: head('Employees')}"></head><body><div th:replace="~{layout :: sidebar}"></div><div class="content"><h1>Employees</h1><table><tr><th>Code</th><th>Name</th></tr><tr th:each="e : "><td th:text=""></td><td th:text=""></td></tr></table></div></body></html>''')
w(tm+'financial/list.html', '''<!DOCTYPE html><html xmlns:th="http://www.thymeleaf.org"><head th:replace="~{layout :: head('Financial Summary')}"></head><body><div th:replace="~{layout :: sidebar}"></div><div class="content"><h1>Financial Summary</h1><table><tr><th>Period</th><th>Net Profit</th></tr><tr th:each="f : "><td th:text=""></td><td th:text=""></td></tr></table></div></body></html>''')

